### ISSUE TITLE
NoSuchMethod

### ISSUE THREAD

**Issue by marcusbb** [chbatey/kafka-unit#24]
Hi there.
I'm getting an unusual problem when I'm testing within my eclipse IDE.
java.lang.NoSuchMethodError: org.apache.kafka.common.protocol.SecurityProtocol.nonTestingValues()Ljava/util/Set;
	at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:443)
	at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:714)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:716)
	at info.batey.kafka.unit.KafkaUnit.startup(KafkaUnit.java:125)
	at info.batey.kafka.unit.KafkaUnitRule.before(KafkaUnitRule.java:36)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

What makes this more unusual is that when I build/compile in my IDE and link kafka-unit project, then this problem goes away.  Meaning I can't simply reference the dependency in my pom.

**Comment by marcusbb** [comment]
Found the problem, it was conflicting kafka client dependency: 
I previously had 0.9.0.0 and 0.9.0.1 fixed the issue.
