### ISSUE TITLE
Can not connect to Zookeeper when create topic

### ISSUE THREAD

**Issue by Muyoo** [chbatey/kafka-unit#33]
Hi 
I receive an exception when I create a topic:

> org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:75)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:57)
	at kafka.utils.ZkUtils.apply(ZkUtils.scala)
	at info.batey.kafka.unit.KafkaUnit.createTopic(KafkaUnit.java:170)
	at info.batey.kafka.unit.KafkaUnit.createTopic(KafkaUnit.java:153)

and my code is like this:
`
import com.google.common.base.Throwables;
import info.batey.kafka.unit.KafkaUnit;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class TestClass {

    private static final int KAFKA_PORT = 2181;
    private static final int ZK_PORT = 9092;

    private static final String SOURCE_TOPIC = "source-topic";
    private static final String ISSUE_TOPIC = "issue-topic";
    private static final String CRASH_TOPIC = "crash-topic";

    private KafkaUnit kafkaServer;

    @Before
    public void setup() {

        try {
            kafkaServer = new KafkaUnit(ZK_PORT, KAFKA_PORT);

            kafkaServer.createTopic(SOURCE_TOPIC);
            kafkaServer.createTopic(ISSUE_TOPIC);
            kafkaServer.createTopic(CRASH_TOPIC);
        } catch (Exception e) {
            Throwables.propagate(e);
        }
        kafkaServer.startup();
    }

    @Test
    public void testConsumer() {
    }

    @After
    public void tearDown() {
        if (null != kafkaServer)
            kafkaServer.shutdown();
    }
}
`

I don't know how to fix this. Any suggestions are thankful!

**Comment by narendrasfo** [comment]
I am also getting same error , is there any way to resolve this

**Comment by 1ambda** [comment]
@Muyoo @narendrasfo you should call `startup` before `createTopic` 

IMO, README should include whole code example including preparing for a kafka server instead of providing partial one
