### ISSUE TITLE
Usage: Error while starting kafka unit server

### ISSUE THREAD

**Issue by bvarghese1** [chbatey/kafka-unit#68]
I am trying to use the kafka-unit maven package to verify if I can use an embedded kafka server for testing. However, I am getting the following error:

```
2019-04-18 10:52:51,581 FATAL KafkaServer: Fatal error during KafkaServer startup. Prepare to shutdown
java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/Base64
	at kafka.utils.CoreUtils$.generateUuidAsBase64(CoreUtils.scala:286)
	at kafka.server.KafkaServer$$anonfun$getOrGenerateClusterId$1.apply(KafkaServer.scala:356)
	at kafka.server.KafkaServer$$anonfun$getOrGenerateClusterId$1.apply(KafkaServer.scala:356)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaServer.getOrGenerateClusterId(KafkaServer.scala:356)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:197)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at info.batey.kafka.unit.KafkaUnit.startup(KafkaUnit.java:149)
	at com.concentricai.dbaggregator.TestDBAggregatorInt.setUp(TestDBAggregatorInt.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.utils.Base64
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 32 more
2019-04-18 10:52:51,582 INFO  KafkaServer: shutting down
2019-04-18 10:52:51,583 DEBUG KafkaScheduler: Shutting down task scheduler.
2019-04-18 10:52:51,584 DEBUG ZkClient: Closing ZkClient...
2019-04-18 10:52:51,584 INFO  ZkEventThread: Terminate ZkClient event thread.
2019-04-18 10:52:51,584 DEBUG ZkConnection: Closing ZooKeeper connected to localhost:56651
2019-04-18 10:52:51,584 DEBUG ZooKeeper: Closing session: 0x16a3194694d0000
```

Here is my test code
```
import info.batey.kafka.unit.KafkaUnit;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class TestDBAggregatorInt {

    KafkaUnit kafkaUnitServer;

    @Before
    public void setUp() throws Exception {
        kafkaUnitServer = new KafkaUnit();
        kafkaUnitServer.startup();
    }

    @After
    public void tearDown() {
        kafkaUnitServer.startup();
    }

    @Test
    public void testKafkaCreateTopic() {
        kafkaUnitServer.createTopic("test");
    }

}
```

And I have added the kafka-unit dependency in my pom.xml as follows:
```
        <dependency>
            <groupId>info.batey.kafka</groupId>
            <artifactId>kafka-unit</artifactId>
            <version>1.0</version>
            <scope>test</scope>
        </dependency>
```

**Comment by bvarghese1** [comment]
Forgot to mention, I have other dependencies such as:
```
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <version>2.1.0</version>
        </dependency>
```

**Comment by atx-bong-soccer** [comment]
I have included all the three dependencies mentioned above but still facing the error. Please let me know, if I am missing something -

  2019-08-16 16:21:33,028 [main] FATAL kafka.server.KafkaServer - Fatal error during KafkaServer startup. Prepare to shutdown
  java.lang.NoClassDefFoundError: org/apache/kafka/common/utils/Base64
	at kafka.utils.CoreUtils$.generateUuidAsBase64(CoreUtils.scala:286)
	at kafka.server.KafkaServer$$anonfun$getOrGenerateClusterId$1.apply(KafkaServer.scala:356)
	at kafka.server.KafkaServer$$anonfun$getOrGenerateClusterId$1.apply(KafkaServer.scala:356)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaServer.getOrGenerateClusterId(KafkaServer.scala:356)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:197)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at info.batey.kafka.unit.KafkaUnit.startup(KafkaUnit.java:149)

**Comment by tianlin** [comment]
Add 1.0.0 kafka-clients to pom to walk around

<dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
</dependency>

**Comment by qaisbadsha** [comment]
I am facing the same issue. Is there no resolution for this?

**Comment by bvarghese1** [comment]
I have migrated to using kafka-streams based test utils and its working fine for me.
