### ISSUE TITLE
Kafka unit - Exception

### ISSUE THREAD

**Issue by niteshthali08** [chbatey/kafka-unit#71]
Recently Kafka unit has started crashing JVM

``
Test attempted to crash JVM with code 1
java.lang.AssertionError: Test attempted to crash JVM with code 1
	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.apache.kafka.common.utils.Exit$2.execute(Exit.java:39)
	at org.apache.kafka.common.utils.Exit.exit(Exit.java:51)
	at kafka.utils.Exit$.exit(Exit.scala:28)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:43)
	at info.batey.kafka.unit.KafkaUnit.startup(KafkaUnit.java:149)
``

I have following dependency in my project

``
info/batey/kafka:kafka-unit-1.0.jar
org/apache/kafka:kafka-clients-1.0.0.jar
``

Any help in this regard will be greatly appreciated.
Thanks in advance!

**Comment by niteshthali08** [comment]
The above exception was encapsulated hence missed the origin one. Posting it below.
`Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at Test.main(Test.java:23)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more`
